---
title: "My Post Title"
date: 2024-10-09
sitemap:
  changefreq: "weekly"
  priority: 0.8

params:
  description: "윤혜민의 포트폴리오"
  author: "Hyemin Youn"
  og_image: "assets/media/logo.svg"  # 대표 이미지 경로

---
