title: 윤혜민의 포트폴리오 # Website name
baseURL: 'https://hyemin-youn.github.io/Hyemin-Youn.github.io/' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: ko
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## FAVICON 설정
############################
params:
  favicon:
    apple_touch_icon: "/apple-touch-icon.png"
    icon32: "/favicon-32x32.png"
    icon16: "/favicon-16x16.png"
    manifest: "/site.webmanifest"
    ico: "/favicon.ico"

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
