menu:
  main:
    - name: "About"
      url: "/about/"
      weight: 100

    - name: "People"
      url: "/people/"
      weight: 200
      children:
        - name: "Professor"
          url: "/author/이경수/"
          weight: 210
        - name: "Members"
          url: "/people/"
          weight: 220

    - name: "Research"
      url: "/publication/"
      weight: 300
      children:
        - name: "Publications"
          url: "/publication/"
          weight: 310
        - name: "Research Fields"
          url: "/field/"
          weight: 320

    - name: "Inform"
      url: "/post/"
      weight: 600
      children:
        - name: "Notifications"
          url: "/notification/"
          weight: 610
        - name: "News"
          url: "/post/"
          weight: 620
        - name: "Event"
          url: "/event/"
          weight: 630

    - name: "Contact"
      url: "/contact/"
      weight: 700
