main:
  - name: Home
    url: ''
    weight: 10
  - name: About
    url: 'https://hyemin-youn.github.io/about/'
    weight: 20
  - name: Project
    url: 'https://hyemin-youn.github.io/Project'
    weight: 30
  - name: Study
    weight: 40
    hasChildren: true
  - parent: Study
    name: JavaScript
    url: 'https://www.youtube.com/watch?v=OdMfUv-BFT4&list=PLRtkynNyEsXnoY9KbbbLF9dPGGARLkCyU'
  - parent: Study
    name: Node.js
    name: 'https://www.youtube.com/watch?v=Tt_tKhhhJqY'

#수정함
  - name: Resources
    weight: 50
    hasChildren: true
  - parent: Resources
    name: Blog
    url: 'https://blog.naver.com/yunemin'
  - name: Contact
    url: 'https://hyemin-youn.github.io/contact/'
    weight: 60
  # - name: Blog
  #   url: 'https://blog.naver.com/yunemin'
  #   weight: 50
  # - name: Contact
  #   url: 'https://hyemin-youn.github.io/contact/'
  #   weight: 60

 # Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

