main:
  # - name: Home
  #   url: ''
  #   weight: 10
  - name: About
    url: about
    weight: 10
  - name: Project
    url: 'https://hyemin-youn.github.io/Project'
    weight: 20

  #parent-child
  - name: Study
    weight: 30
    hasChildren: true
  - parent: Study
    name: JavaScript
    url: 'https://www.youtube.com/watch?v=OdMfUv-BFT4&list=PLRtkynNyEsXnoY9KbbbLF9dPGGARLkCyU'
  - parent: Study
    name: Node.js
    url: 'https://www.youtube.com/watch?v=Tt_tKhhhJqY'

  #parent-child
  - name: Resources
    weight: 400
    hasChildren: true
  - parent: Resources
    name: Blog
    url: 'https://blog.naver.com/yunemin'
    
  - name: Contact
    url: 'https://hyemin-youn.github.io/contact/'
    weight: 50
 


 # Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

