main:
  - name: Home
    url: ''
    weight: 1
  - name: Contact
    url: ''
    weight: 2
  - name: Project
    url: ''
    weight: 3 
  - name: Study
    url: ''
    weight: 4
  - name: Blog
    url: 'https://blog.naver.com/yunemin'
    weight: 5

 # Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

