# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A college student of Jeonbuk National University.'
    twitter: 'Hyemin-Youn'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    show_day_night: true
    show_search: true
    show_theme_chooser: true
    show_language: true
    show_logo: true
    
 

    

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license: 
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
 

# Localization
locale:
  date_format: 'Oct 6, 2024'
  time_format: '11:00 AM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  search:
    provider: wowchemy
    wowchemy:
      min_length: 1
      threshold: 0.3
      # app_id: ''
      # api_key: ''
      # index_name: ''
      # show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

sections:
  contact:
    content:
      title: "Contact"
      text: "This is a contact section."
      email: "hyemin9973@gmail.com"
      phone: "+82-10-9973-5063"
      address:
        street: "전북대학교 공과대학 7호관"
        city: "전주시"
        region: "전라북도"
        postcode: "54896"
        country: "대한민국"
        country_code: "KO"
